# Generated by Django 5.0.6 on 2024-07-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('в наличии', 'В наличии'), ('нет в наличии', 'нет в наличии')], max_length=255, null=True, verbose_name='Статус'),
        ),
    ]
