# Generated by Django 5.0.6 on 2024-07-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('WHITE', 'WHITE'), ('BLACK', 'BLACK'), ('GRAY', 'GRAY'), ('BROWN', 'BROWN')], max_length=255, null=True, verbose_name='Цвета'),
        ),
    ]
