# Generated by Django 5.0.6 on 2024-07-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='now_price',
            field=models.IntegerField(default=1, verbose_name='Цена сейчас'),
            preserve_default=False,
        ),
    ]
