# Generated by Django 5.0.6 on 2024-07-15 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0002_slider_now_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='now_price',
        ),
    ]
