# Generated by Django 5.0.6 on 2024-07-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0003_remove_slider_now_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.CharField(max_length=255, verbose_name='Название (доставки)')),
                ('delivery_desc', models.CharField(max_length=500, verbose_name='Описание (доставки)')),
                ('money', models.CharField(max_length=255, verbose_name='Название (гарантия на возврат)')),
                ('money_desc', models.CharField(max_length=500, verbose_name='Описание (гарантия на возврат)')),
                ('support', models.CharField(max_length=255, verbose_name='Название (онлайн поддержка)')),
                ('support_desc', models.CharField(max_length=500, verbose_name='Описание (онлайн поддержка)')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
            },
        ),
    ]
