# Generated by Django 5.0.6 on 2024-07-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billings',
            name='city',
            field=models.CharField(default=1, max_length=255, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billings',
            name='home',
            field=models.CharField(default=1, max_length=255, verbose_name='Дом'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billings',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
    ]
